import { useCallback, useEffect, useRef, useState } from "react";
import { explainCircuit, type ExplainResult } from "../../services/circuitExplainService";
import { useEntitlements } from "../../utils/entitlementManager";
import type { LegacyCircuitState } from "../builder/types";
import "../../styles/circuit-explain.css";

interface CircuitExplainPanelProps {
  isOpen: boolean;
  circuitState: LegacyCircuitState | null;
  onClose: () => void;
  /** Called when the user taps "Upgrade to Pro" inside the gate screen. */
  onUpgrade?: () => void;
}

export function CircuitExplainPanel({
  isOpen,
  circuitState,
  onClose,
  onUpgrade,
}: CircuitExplainPanelProps) {
  const { isPremiumOrAbove } = useEntitlements();
  const [result, setResult] = useState<ExplainResult | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [hasError, setHasError] = useState(false);

  // Track the circuit snapshot we last generated an explanation for so we
  // don't re-run automatically on every minor state tick.
  const lastExplainedRef = useRef<string | null>(null);

  const runExplain = useCallback(async () => {
    if (!circuitState) return;
    setIsLoading(true);
    setHasError(false);
    try {
      const explanation = await explainCircuit(circuitState);
      setResult(explanation);
      lastExplainedRef.current = circuitState.updatedAt;
    } catch {
      setHasError(true);
    } finally {
      setIsLoading(false);
    }
  }, [circuitState]);

  // Run explanation when the panel opens (only if we haven't explained this
  // snapshot yet, or if the circuit has changed since the last run).
  useEffect(() => {
    if (!isOpen || !isPremiumOrAbove || !circuitState) return;
    if (lastExplainedRef.current === circuitState.updatedAt && result !== null) return;
    runExplain();
  }, [isOpen, isPremiumOrAbove, circuitState, result, runExplain]);

  // Reset panel state when closed so the next open starts fresh.
  useEffect(() => {
    if (!isOpen) {
      setResult(null);
      setHasError(false);
      setIsLoading(false);
      lastExplainedRef.current = null;
    }
  }, [isOpen]);

  const handleKeyDown = (e: React.KeyboardEvent<HTMLDivElement>) => {
    if (e.key === "Escape") onClose();
  };

  if (!isOpen) return null;

  return (
    <>
      {/* Backdrop — tap anywhere outside the panel to dismiss */}
      <div
        className="circuit-explain-backdrop"
        onClick={onClose}
        aria-hidden="true"
      />

      <div
        className="circuit-explain-panel"
        role="dialog"
        aria-modal="true"
        aria-label="Circuit explanation"
        onKeyDown={handleKeyDown}
      >
        {/* Header */}
        <div className="circuit-explain-panel__header">
          <span className="circuit-explain-panel__header-icon" aria-hidden="true">
            🔍
          </span>
          <div>
            <div className="circuit-explain-panel__header-title">Explain Circuit</div>
            <div className="circuit-explain-panel__header-subtitle">
              AI-powered circuit analysis
            </div>
          </div>
          <div className="circuit-explain-panel__header-meta">
            {result && (
              <span
                className={`circuit-explain-panel__source-badge circuit-explain-panel__source-badge--${result.source}`}
                title={result.source === "ai" ? "Generated by AI backend" : "Generated locally"}
              >
                {result.source === "ai" ? "AI" : "Local"}
              </span>
            )}
            <button
              type="button"
              className="circuit-explain-panel__close"
              onClick={onClose}
              aria-label="Close circuit explanation"
              title="Close"
            >
              ✕
            </button>
          </div>
        </div>

        {/* Body */}
        {!isPremiumOrAbove ? (
          /* Pro gate */
          <div className="circuit-explain-panel__gate">
            <span className="circuit-explain-panel__gate-icon" aria-hidden="true">🔒</span>
            <div className="circuit-explain-panel__gate-title">Pro Feature</div>
            <p className="circuit-explain-panel__gate-text">
              The AI Circuit Explanation Engine is available on the Premium plan
              and above. Upgrade to unlock instant circuit analysis, current-flow
              walkthroughs, component-role breakdowns, and mistake detection.
            </p>
            <button
              type="button"
              className="circuit-explain-panel__gate-btn"
              onClick={onUpgrade}
              aria-label="Upgrade to Pro to unlock circuit explanations"
            >
              Upgrade to Pro →
            </button>
          </div>
        ) : isLoading ? (
          /* Loading */
          <div className="circuit-explain-panel__loading" aria-live="polite" aria-busy="true">
            <div className="explain-spinner" aria-hidden="true" />
            <span>Analyzing your circuit…</span>
          </div>
        ) : hasError ? (
          /* Error / unavailable */
          <div className="circuit-explain-panel__unavailable" role="alert">
            <span className="circuit-explain-panel__unavailable-icon" aria-hidden="true">⚠️</span>
            <div className="circuit-explain-panel__unavailable-title">
              Explanation unavailable
            </div>
            <p className="circuit-explain-panel__unavailable-text">
              The explanation engine could not generate a result right now.
              Check that you have an active circuit and try again.
            </p>
            <button
              type="button"
              className="circuit-explain-panel__regenerate"
              onClick={runExplain}
            >
              ↺ Retry
            </button>
          </div>
        ) : result ? (
          /* Explanation content */
          <>
            <div className="circuit-explain-panel__body">
              {/* Summary */}
              <section className="explain-section" aria-label="Summary">
                <div className="explain-section__title">Summary</div>
                <p className="explain-section__text">{result.summary}</p>
              </section>

              {/* Current flow */}
              <section className="explain-section" aria-label="Current flow">
                <div className="explain-section__title">Current Flow</div>
                <p className="explain-section__text">{result.currentFlow}</p>
              </section>

              {/* Component roles */}
              {result.componentRoles.length > 0 && (
                <section className="explain-section" aria-label="Component roles">
                  <div className="explain-section__title">Component Roles</div>
                  <div className="explain-roles-list">
                    {result.componentRoles.map((item) => (
                      <div key={item.component} className="explain-role-item">
                        <span className="explain-role-item__label">{item.component}</span>
                        <span className="explain-role-item__desc">{item.role}</span>
                      </div>
                    ))}
                  </div>
                </section>
              )}

              {/* Expected behavior */}
              <section className="explain-section" aria-label="Expected behavior">
                <div className="explain-section__title">Expected Behavior</div>
                <p className="explain-section__text">{result.expectedBehavior}</p>
              </section>

              {/* Common mistakes */}
              <section className="explain-section" aria-label="Common mistakes">
                <div className="explain-section__title">Common Mistakes</div>
                <ul className="explain-mistakes-list">
                  {result.commonMistakes.map((mistake, i) => (
                    // eslint-disable-next-line react/no-array-index-key
                    <li key={i} className="explain-mistake-item">{mistake}</li>
                  ))}
                </ul>
              </section>
            </div>

            {/* Footer */}
            <div className="circuit-explain-panel__footer">
              <button
                type="button"
                className="circuit-explain-panel__regenerate"
                onClick={runExplain}
                disabled={isLoading}
                title="Re-generate explanation for the current circuit"
              >
                ↺ Regenerate
              </button>
            </div>
          </>
        ) : null}
      </div>
    </>
  );
}

export default CircuitExplainPanel;
